### ISSUE TITLE
UI improvements to show more information

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-explorer#16]
PR link: https://github.com/HathorNetwork/hathor-explorer/pull/17
Wallet lib PR link: https://github.com/HathorNetwork/hathor-wallet-lib/pull/42

- Tokens list;
- Add height to transaction detail;
- Nonce in tx detail shouldn't have `toString()`. It's not working for merged mining blocks;
- Add height to statistics
- Should we differ in tx detail the block from merged mining? 
  - Set the type as 'Merged Mined Block' and the normal as 'Block'? Yes
  - Show aux_pow data instead of the nonce? No

**Comment by msbrogli** [comment]
Both PRs were merged.
