### ISSUE TITLE
feat: Add support for search by address

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-explorer#18]
PR: https://github.com/HathorNetwork/hathor-explorer/pull/21
MR full node: https://gitlab.com/HathorNetwork/hathor-python/-/merge_requests/369
PR lib: https://github.com/HathorNetwork/hathor-wallet-lib/pull/49

## Pending decisions

Should we update the Desktop Wallet or just remove the search from there?

## Benchmark:

https://ltc5.trezor.io/address/MR7EkbwAzGv6e2JYn273fzAUY1V4s97RzA

**Comment by pedroferreira1** [comment]
**UI/UX Discussions**
1. On the benchmark the search field disappears on mobile, should we keep ours on the menu, or move/hide?

![image](https://user-images.githubusercontent.com/3298774/73202148-36f16900-4119-11ea-8ff0-647e43b7c376.png)
![image](https://user-images.githubusercontent.com/3298774/73202071-13c6b980-4119-11ea-82f2-705276c62faf.png)
![image](https://user-images.githubusercontent.com/3298774/73202184-407ad100-4119-11ea-9cd8-cfc240c103ee.png)

2. On the benchmark we have a summary of the address (with total received, total sent and # of txs) and the list of all transactions with their inputs/outputs.

I think we could also have the summary but we could have a paginated list of txs/blocks without the inputs/outputs but the user would click on the element of the list to access the detail, like we have in the block/tx list.

![image](https://user-images.githubusercontent.com/3298774/73202205-4d97c000-4119-11ea-9dca-6641e2cb2a1e.png)
![image](https://user-images.githubusercontent.com/3298774/73202230-5d170900-4119-11ea-9d0e-26fd4d375df7.png)

**Comment by obiyankenobi** [comment]
1) I think we should keep the search bar on mobile.

2) I agree, we could have the summary and only the list of blocks/txs.

**Comment by msbrogli** [comment]
Great benchmark!

1. I agree with @obiyankenobi that we should keep the search bar on mobile.

2. I also agree with both of you. A single list with all blocks and transactions.
