### ISSUE TITLE
Create LICENSE file and add license header in all code files

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-explorer#3]

**Comment by jansegre** [comment]
I wouldn't bother adding a license header to every file, I don't think this is that common now a days.

**Comment by pedroferreira1** [comment]
> I wouldn't bother adding a license header to every file, I don't think this is that common now a days.

Even though it's not a consensus that adding this header is necessary, some big projects have it. I don't mind not having it, I just think we should just be consistent. We should either have the header in all our projects or in none.

The first MR that added a license file had a small discussion about it https://gitlab.com/HathorNetwork/thin-wallet/merge_requests/39#note_157599105

@jansegre @obiyankenobi @msbrogli

**Comment by obiyankenobi** [comment]
It doesn't hurt to add it and that's what we've been doing in all repos.

**Comment by jansegre** [comment]
I missed that discussion. But I'm all for consistency. If we're already doing it then fine.
